name: Release Notification

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: |
            🚀 New version deployed to production!
            Version: ${{ github.event.release.tag_name }}
            Release: ${{ github.event.release.name }}
            Changes: ${{ github.event.release.body }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        with:
          args: |
            🎉 **Production Deployment Complete**
            **Version:** `${{ github.event.release.tag_name }}`
            **Release:** ${{ github.event.release.name }}
            **Repository:** ${{ github.repository }}
            **View Release:** ${{ github.event.release.html_url }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚀 Production Deployment - ${{ github.event.release.tag_name }}"
          to: ${{ secrets.NOTIFICATION_EMAIL }}
          from: "GitHub Actions <${{ secrets.EMAIL_USERNAME }}>"
          body: |
            New version has been deployed to production:
            
            Version: ${{ github.event.release.tag_name }}
            Release: ${{ github.event.release.name }}
            Repository: ${{ github.repository }}
            
            Release Notes:
            ${{ github.event.release.body }}
            
            View Release: ${{ github.event.release.html_url }}
